apiVersion: batch/v1
kind: Job
metadata:
  name: newman-job-k8
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: newman
        image: shrawan7777/my_app:latest
        command: ["sh", "-c", "mkdir -p /reports && newman run my-api-tests.json -r html --reporter-html-export /reports/newman-report.html"]


      restartPolicy: Never
  backoffLimit: 1
