apiVersion: batch/v1
kind: Job
metadata:
  name: newman-job-k8
spec:
  template:
    spec:
      containers:
      - name: newman
        image: shrawan7777/my_app:latest
        command: ["newman", "run", "my-api-tests.json", "-r", "html", "--reporter-html-export", "/reports/newman-report.html"]
        volumeMounts:
        - name: report-volume
          mountPath: /reports
      restartPolicy: Never
      volumes:
      - name: report-volume
        emptyDir: {}
