apiVersion: batch/v1
kind: Job
metadata:
  name: newman-job-k8
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: newman
        image: shrawan7777/my_app:latest
        command: ["newman", "run", "my-api-tests.json"]
      restartPolicy: Never
  backoffLimit: 1
