apiVersion: batch/v1
kind: Job
metadata:
  name: newman-job-k8
spec:
  template:
    spec:
      containers:
      - name: newman
        image: my_app:latest
        imagePullPolicy: IfNotPresent   # important for local KinD images
        command: [
          "newman", "run", "/etc/newman/my-api-tests.json",
          "-r", "cli,html", 
          "--reporter-html-export", "/reports/newman-report.html"
        ]
        volumeMounts:
        - name: report-volume
          mountPath: /reports
      restartPolicy: Never
      volumes:
      - name: report-volume
        emptyDir: {}
  backoffLimit: 1
