apiVersion: batch/v1
kind: Job
metadata:
  name: newman-job-k8
spec:
  template:
    spec:
      containers:
      # Main container runs Newman tests
      - name: newman
        image: shrawan7777/my_app:latest
        command: ["newman", "run", "/etc/newman/my-api-tests.json", "-r", "html", "--reporter-html-export", "/reports/newman-report.html"]
        volumeMounts:
        - name: report-volume
          mountPath: /reports

      # Sidecar container keeps pod alive
      - name: report-holder
        image: busybox
        command: ["sh", "-c", "sleep 3600"]   # keeps pod alive for 1 hour
        volumeMounts:
        - name: report-volume
          mountPath: /reports

      restartPolicy: Never
      volumes:
      - name: report-volume
        emptyDir: {}
  backoffLimit: 1
