name: Run Postman Tests on KinD

on:
  push:
    branches: [ main ]

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image locally
      - name: Build Docker image
        run: docker build -t my_app:latest .

      # 4. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # 5. Install KinD
      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # 6. Create KinD cluster
      - name: Create KinD cluster
        run: kind create cluster --name test-cluster

      # 7. Load Docker image into KinD
      - name: Load Docker image into KinD
        run: kind load docker-image my_app:latest --name test-cluster

      # 8. Apply Newman Job
      - name: Apply Newman Job
        run: kubectl apply -f newman-job-k8.yaml

      # 9. Wait for pod to exist
      - name: Wait for Newman pod
        run: |
          echo "Waiting for Newman pod to appear..."
          MAX_WAIT=30
          COUNT=0
          POD_NAME=""
          while [[ -z "$POD_NAME" && $COUNT -lt $MAX_WAIT ]]; do
              kubectl get pods -A
              POD_NAME=$(kubectl get pods -l job-name=newman-job-k8 -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
              COUNT=$((COUNT + 1))
              sleep 2
          done
          if [[ -z "$POD_NAME" ]]; then
              echo "Pod never appeared. Printing debug info:"
              kubectl get pods -A
              kubectl describe job newman-job-k8
              exit 1
          fi
          echo "Pod detected: $POD_NAME"

      # 10. Wait for container to be running
      - name: Wait for container
        run: |
          echo "Waiting for container to be running..."
          kubectl wait --for=condition=Ready pod/$POD_NAME --timeout=60s || echo "Container not ready yet"

      # 11. Stream logs
      - name: Stream Newman logs
        run: |
          echo "Streaming logs from pod: $POD_NAME"
          kubectl logs -f $POD_NAME -c newman || echo "Logs not available yet"

      # 12. Copy HTML report (optional)
      - name: Copy Newman HTML report
        run: |
          kubectl cp $POD_NAME:/reports/newman-report.html ./newman-report.html -c newman || echo "Report copy failed"

      # 13. Upload HTML report
      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html
